#ifndef __WATERLEVEL_H
#define __WATERLEVEL_H
#include <drv_gpio.h>

#define LOW_LEVEL_GPIO_GROUP 		C
#define LOW_LEVEL_GPIO_PIN 			1
#define LOW_LEVEL_PIN  				GET_PIN(LOW_LEVEL_GPIO_GROUP, LOW_LEVEL_GPIO_PIN)
#define HIGH_LEVEL_GPIO_GROUP 		C
#define HIGH_LEVEL_GPIO_PIN 		1
#define HIGH_LEVEL_PIN  			GET_PIN(HIGH_LEVEL_GPIO_GROUP, HIGH_LEVEL_GPIO_PIN)
#define VALVE_RCOLD_GPIO_GROUP 		C
#define VALVE_RCOLD_GPIO_PIN 		1
#define VALVE_RCOLD_PIN  			GET_PIN(VALVE_RCOLD_GPIO_GROUP, VALVE_RCOLD_GPIO_PIN)
#endif